version: '3.9'
services:
  web:
    build:
      context: .
      args:
        RUBY_VERSION: ${RUBY_VERSION}
    ports:
      - "5000:3000"
    volumes:
      - ".:/workspace"
    env_file:
      - .env
    depends_on:
      - db
      - mailcatcher
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ${APP_NAME}_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mailcatcher:
    image: yappabe/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"
volumes:
  postgres_data:
