default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: <%= ENV.fetch("APP_NAME") %>_development

test:
  <<: *default
  database: <%= ENV.fetch("APP_NAME") %>_test

production:
  <<: *default
  database: <%= ENV.fetch("APP_NAME") %>_production
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>